name: hexlet-check
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
jobs:
  build:
    runs-on: ubuntu [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Hexlet project check
        uses: hexlet/project-action@release
        with:
          hexlet-id: ${{ 11035 }}
